added artillery yml; created connection to Postgres; changed GET queries from MySQL to PostgreSQL
AirJEC/AirJEC-reservations-Emily pull request #1
Opened 2018-06-29 22:32 UTC by etcaples

(https://trello.com/c/tizOTtWt/11-write-new-database-queries-in-postgres-med)
(https://trello.com/c/eFsDkoOy/18-make-a-csv-file-of-fake-data-records-for-10-million-rooms-records-lg)
(https://trello.com/c/7lmiFQ6O/17-write-functions-to-create-populate-fake-data-lg)
(https://trello.com/c/LQE9IzIM/12-figure-out-aarons-post-get-requests-for-reservations-module-med)
(https://trello.com/c/kZM8lnP7/22-create-artillery-yml-file-sm-25m)

2018-06-29 22:43 UTC, ChuaJ requested changes
MINOR STYLE  FIX. Otherwise, good job!

2018-06-29 22:43 UTC, ChuaJ commented on database/pgdb/index.js
> +const moment = require('moment');
Have all require statements at the top of the file! -style guide

2018-06-29 23:09 UTC, etcaples commented
@ChuaJ can you take a look at my changes? Thanks :)

2018-06-30 17:08 UTC, ChuaJ approved these changes

2018-07-03 02:11 UTC, merged